# Generated by Django 4.1 on 2022-11-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kozanApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArea', models.CharField(max_length=50)),
                ('encargado', models.CharField(max_length=50)),
                ('piso', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('capacitacion', models.CharField(max_length=50)),
            ],
        ),
    ]
