# Generated by Django 4.1 on 2022-12-02 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kozanApp', '0002_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='aarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kozanApp.area'),
        ),
    ]
