# Generated by Django 4.1 on 2022-12-02 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kozanApp', '0003_empleado_aarea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['nombreArea'], 'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterModelTable(
            name='area',
            table='area',
        ),
    ]
