# Generated by Django 4.1 on 2022-12-03 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kozanApp', '0005_rename_aarea_empleado_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipos',
            old_name='tipo',
            new_name='nequipo',
        ),
    ]
