# Generated by Django 4.1 on 2022-12-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kozanApp', '0006_rename_tipo_equipos_nequipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='capacitacion',
            field=models.CharField(choices=[('NO', 'NO CAPACITADO'), ('SI', 'HAY CAPACITACION')], max_length=2),
        ),
    ]
