# Generated by Django 4.1 on 2022-12-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kozanApp', '0007_alter_area_capacitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='capacitacion',
            field=models.CharField(choices=[('NO', 'NO CAPACITADO'), ('SI', 'HAY CAPACITACION')], max_length=20),
        ),
    ]
