# Generated by Django 4.1 on 2022-12-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kozanApp', '0008_alter_area_capacitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='capacitacion',
            field=models.CharField(max_length=2),
        ),
    ]
