# Generated by Django 4.1 on 2022-12-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kozanApp', '0009_alter_area_capacitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('numero', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
